### PR TITLE
Properly escape GitExe and CygPathExe for WSL

### LINKED ISSUE #194: Execution fails if using WSL and username contains spaces
## Describe the Bug

The execution currently fails if using WSL and the username contains spaces. This is due to improper escaping of space characters in GitExe and CygPathExe.

## Steps to Reproduce

1. Create a Windows username with spaces on the name, so its .nuget folder is in a path that contains spaces, such as `C:\Users\Example User\.nuget\packages\gitinfo\2.2.0\build`.
2. Attempt to run a project that has GitInfo setup.

On the output console the following will be displayed:
```
4>"C:\Users\Example" is not recognized as an internal or external command,
4>operable program or batch file.
4>C:\Users\Example User\.nuget\packages\gitinfo\2.2.0\build\GitInfo.targets(1088,3): warning MSB3073: Command "..." exited with error code 9009.
4>"--version" is not recognized as an internal or external command,
4>operable program or batch file.
4>C:\Users\Example User\.nuget\packages\gitinfo\2.2.0\build\GitInfo.targets(203,3): warning MSB3073: Command "..." exited with error code 9009.
4>C:\Users\Example User\.nuget\packages\gitinfo\2.2.0\build\GitInfo.targets(212,3): error : Failed to run `git --version`. Git may not be properly installed: 
4>C:\Users\Example User\.nuget\packages\gitinfo\2.2.0\build\GitInfo.targets(212,3): error :  "--version" is not recognized as an internal or external command,;operable program or batch file.
```

## Expected Behavior

GitInfo should run just fine.

## Version Info

Present in latest 2.2.0

### PR DESCRIPTION
**Pull request by socram8888**
Fixes #194

### CODE REVIEW

**Comment by kzu** [comment]
I can't see how *removing* the double quotes is fixing the issue. Could you explain how/why it would work? (or even better, could you record a short gif that showcases it working? you can use the free licecap)

**Comment by socram8888** [comment]
Quotes have not been removed - instead, they've been moved to the variable definition itself (see lines 1098-1099)

The reason is twofold: 
 - it makes much easier to use those variables - you no longer need to be thinking if the variable needs to be escaped or not in the rest of the code, if it is already escaped beforehand.
 -  there is a considerable amount of places where the variable GitExe wasn't quoted, so it results in a smaller diff to remove the few places where the quotes existed and edit the definition, rather than add them to all the places where they were missing

**Comment by kzu** [comment]
Looks good! As soon as you sign the CLA, I'll merge this.

Thanks for your contribution!

**Comment by kzu** [comment]
Would you mind rebasing on top of main to resolve conflicts?

**Pull request merged**
